[server]
host: 0.0.0.0
port: 7126
klippy_uds_address: /home/per/printer_data/comms/dual_filament.sock

[authorization]
trusted_clients:
    192.168.0.0/16
    10.0.0.0/8
    127.0.0.0/8
    169.254.0.0/16
    172.16.0.0/12
    FC00::/7
    FE80::/10
    ::1/128
cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://192.168.50.119
    *://192.168.50.119:*
    *://192.168.50.119:8881
    *://192.168.50.119:8082
    *://192.168.50.119:80
    *://my.mainsail.xyz
    *://app.fluidd.xyz

[octoprint_compat]

[history]

[file_manager]
enable_object_processing: False

[update_manager mainsail-dual-filament]
path: /home/per/mainsail-dual-filament
repo: mainsail-crew/mainsail
channel: stable
type: web
persistent_files:
    config.json
